# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('option_value', models.IntegerField(default=10)),
                ('option_weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=200)),
                ('value_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='option_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prop_jeu.OptionType'),
        ),
    ]
